baseURL = 'https://example.org/'
languageCode = 'de-DE'
title = 'Himmelsteil Papeterie'
[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10
[[menu.main]]
identifier = "about"
name = "Über mich"
url = "/"
weight = 20
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 30
[[menu.main]]
identifier = "shop"
name = "Shop"
url = "/shop"
weight = 40
[[menu.main]]
identifier = "contact"
name = "Kontakt"
url = "/kontakt"
weight = 50
[[menu.footer]]
identifier = "legalNotice"
name = "Impressum"
url = "/impressum"
weight = 60
[[menu.gooter]]
identifier = "dataProtection"
name = "Datenschutz"
url = "/datenshutz"
weight = 70
[[menu.footer]]
identifier = "contact"
name = "Kontakt"
url = "/kontakt"
weight = 80
[[menu.footer]]
identifier = "agb"
name = "AGB"
url = "/agb"
weight = 90