baseURL = 'https://example.org/'
languageCode = 'de-DE'
title = 'Himmelsteil Papeterie'
[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10
[[menu.main]]
identifier = "about"
name = "Über mich"
url = "/"
weight = 20
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 30
[[menu.main]]
identifier = "shop"
name = "Shop"
url = "/shop"
weight = 40
[[menu.main]]
identifier = "contact"
name = "Kontakt"
url = "/contact"
weight = 50