name: Deploy Hugo Site to IONOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build site
      run: hugo --minify

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: public
        path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: public

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to IONOS via SFTP
      env:
        RSYNC_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        sshpass -p "$RSYNC_PASSWORD" rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./public/ u112847919@access968851051.webspace-data.io:/kunden/homepages/7/d968851051/htdocs/
