name: Deploy Hugo Site to IONOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build site
      run: hugo --minify

    - name: Check if public directory exists after build
      run: |
        if [ ! -d "./public" ]; then
          echo "Error: The public directory was not created during the Hugo build."
          exit 1
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: public
        path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: public

    - name: Check contents of downloaded artifacts
      run: |
        if [ ! -d "./public" ]; then
          echo "Error: The public directory was not found after downloading the artifact."
          exit 1
        fi
        ls -la ./public

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Deploy to IONOS via SFTP with lftp
      env:
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        SFTP_SERVER: access968851051.webspace-data.io
        SFTP_PORT: 22
        TARGET_DIR: /kunden/homepages/7/d968851051/htdocs/
      run: |
        lftp -c "set sftp:connect-program 'ssh -a -x -o StrictHostKeyChecking=no'; \
          open -u $SFTP_USERNAME,$SFTP_PASSWORD sftp://$SFTP_SERVER:$SFTP_PORT; \
          mirror -R ./public $TARGET_DIR"
