name: Deploy Hugo Site to IONOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Hugo
      run: sudo apt-get install hugo

    - name: Build site
      run: hugo

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: public
        path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: public

    - name: Deploy to IONOS via SFTP
      env:
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        SFTP_SERVER: access968851051.webspace-data.io
        SFTP_PORT: 22
        TARGET_DIR: / # Change if your target directory is different
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp
        lftp -c "set sftp:connect-program 'ssh -a -x -o StrictHostKeyChecking=no'; \
          open -u $SFTP_USERNAME,$SFTP_PASSWORD sftp://$SFTP_SERVER:$SFTP_PORT; \
          mirror -R ./public $TARGET_DIR"
