name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Ändere dies, falls du einen anderen Branch verwendest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Hugo
      run: |
        sudo apt-get install hugo

    - name: Build Hugo
      run: |
        hugo

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}          # Server-IP
        username: ${{ secrets.SSH_USERNAME }}    # Benutzername
        key: ${{ secrets.SSH_PRIVATE_KEY }}      # Privater SSH-Schlüssel
        port: 22                                   # SSH-Port, falls anders, ändere es
        source: "./public/*"
        target: "/var/www/himmelsteil/himmelsteil"            # Zielverzeichnis auf dem Server

